### testing api call

### User

###Get User
GET http://localhost:8000/api/v1/users
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvbUBnbWFpbC5jb20iLCJpYXQiOjE3NDc0Nzc2ODQsImV4cCI6MTc0NzU2NDA4NH0.C-eiwVytGQpLKKG1zfa8UCeNLoPCcGAG1E4ZsqW8BxQ


###Post new User
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
    "name": "Hom",
    "email": "hom@gmail.com",
    "password": "123"
}

###Login User
POST http://localhost:8000/api/v1/users/login
Content-Type: application/json

{
    "email": "hom@gmail.com",
    "password": "123"
}